package com.aicode.reviewer.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * Suggestion entity representing specific code improvement recommendations
 * generated by the AI review. Each suggestion is tied to a review and can
 * include original code, suggested code, and explanations.
 *
 * @author AI Code Reviewer Team
 */
@Entity
@Table(name = "review_suggestions")
@EntityListeners(AuditingEntityListener.class)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReviewSuggestion {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "review_id", nullable = false)
    private Review review;

    @Column(nullable = false, length = 50)
    private String category;

    @Column(nullable = false, length = 20)
    @Builder.Default
    private String severity = "INFO";

    @Column(name = "line_start")
    private Integer lineStart;

    @Column(name = "line_end")
    private Integer lineEnd;

    @Lob
    @Column(nullable = false)
    private String message;

    @Column(name = "original_code", columnDefinition = "TEXT")
    private String originalCode;

    @Column(name = "suggested_code", columnDefinition = "TEXT")
    private String suggestedCode;

    @Column(columnDefinition = "TEXT")
    private String explanation;

    @Column(name = "is_applied", nullable = false)
    @Builder.Default
    private boolean applied = false;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}